# Configurations
title:            Wuhao's Blog
longtitle:
author:           Wuhao
email:            wuhao.code@gmail.com
description: >
  天气不错.

version:          1.0
gitbook_version:  3.2.3

url:              'www.fivehow.com'
baseurl:          '/'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

#kramdown:
#  syntax_highlighter:     true
#  auto_ids:               true
#  input:                  GFM
#  math_engine:            mathjax
#  smart_quotes:           lsquo,rsquo,ldquo,rdquo
#  toc_levels:             1..6
#    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
