# Configurations
title:            Wuhao's Blog
longtitle:
author:           Wuhao
email:            wuhao.code@gmail.com
description: >
  天气不错.

version:          1.0
gitbook_version:  3.2.3

url:              'https://fivehow.com'
baseurl: ""  # 本地调试时设置为空
rss:              RSS

# markdown render engine.
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
